CREATE TABLE Bin (
  id SERIAL PRIMARY KEY,
  path VARCHAR(10) NOT NULL
);

CREATE TABLE Request (
  id SERIAL PRIMARY KEY,
  bin_id INTEGER REFERENCES Bin(id) NOT NULL,
  mongodb_doc_id VARCHAR(24) NOT NULL
);
