DROP DATABASE request_bin;
CREATE DATABASE request_bin;

\c request_bin

CREATE TABLE Bins (
  id SERIAL PRIMARY KEY,
  path VARCHAR(10) NOT NULL
);

CREATE TABLE Requests (
  id SERIAL PRIMARY KEY,
  bin_id INTEGER REFERENCES Bins(id) ON DELETE CASCADE NOT NULL,
  mongodb_doc_id VARCHAR(24) NOT NULL
);